### ISSUE TITLE
How to obtain trn_X_Xf.txt, trn_X_Y.txt, tst_X_Xf.txt, tst_X_Y.txt

### ISSUE THREAD

**Issue by xieyujia000** [Extreme-classification/ECLARE#1]
Hi,

To run `run_ECLARE.sh`, it seems four additonal data files `trn_X_Xf.txt, trn_X_Y.txt, tst_X_Xf.txt, tst_X_Y.txt` is needed. However, I cannot find them from the provided download link for all three datasets (and also not in the dataset webpage http://manikvarma.org/downloads/XC/XMLRepository.html). Could you please point me to where the data files are, or how can I generate the input data?

Also, in `run_ECLARE.sh` line 32, `json.load(open('${model_type}/$dataset.json')`. May I ask where I can find this JSON file?

Thanks a lot!

**Comment by anshumitts** [comment]
@xieyujia000 , Please use BoW link for the dataset and run the pipeline as instructed. ECLARE's data processing pipeline will generate these files for you.

**Comment by anshumitts** [comment]
Alternatively, you can use [pyxclib](https://github.com/kunaldahiya/pyxclib) to read train.txt (or test.txt) and generate these files (trn_X_Xf.txt, trn_X_Y.txt or tst_X_Xf.txt, tst_X_Y.txt) by yourself.

**Comment by xieyujia000** [comment]
Thanks! It turns out to be something wrong with my path configure. Problem solved!

**Comment by jellchou** [comment]
I have generate trn_X_Xf.txt trn_X_Y.txt tstX_X_Xf.txt tst_X_Y.txt.
but not Xf.txt.
How about Xf.txt
