### ISSUE TITLE
Application to long document XC

### ISSUE THREAD

**Issue by trpstra** [Extreme-classification/ECLARE#2]
Thanks for this amazing work.

I am curious to hear your thoughts on if and how this method can be applied to long document classification (>10K tokens, like e.g. patent applications) instead of short text. At first sight it seems the simple composition of token embeddings in the document embedding module may be problematic, and may require at least something like a conv layer. Are there other components in the model architecture that you suspect would be a problem? Have you maybe tried the method on longer documents than product titles? I would be grateful for any insights you can share.

Cheers!

**Comment by anshumitts** [comment]
Hi @onclue, as far as documents consist of text you can use BoW similar to short text as a baseline. After that feel free to modify code for any complicated encoder architecture. As per our experiments, ECLARE gives good accuracy on long text as well. 
In summary, the Focus of ECLARE is short text documents but it can give good accuracy in full text as well.

**Comment by trpstra** [comment]
Thanks for the feedback, I'll give that a try.
