### ISSUE TITLE
ablout the 1-vs-all label classifier Wl

### ISSUE THREAD

**Issue by wangchichi1999** [Extreme-classification/ECLARE#4]
![GZ5VPURXKDGYG Q64C_(7NY](https://user-images.githubusercontent.com/62172616/119322882-af861c80-bcb0-11eb-986e-76d9dc8665ed.png)
Hi! Eclare is absolutely an amazing work！
After reading I was a little bit confused about the one-vs-all label classifier Wl. As you mentioned in the paper, Wl is a vector generated by z1, z2, and refinement vector z3.
So I was wondering how it could accomplish the classification task（like input a sentence and judge whether it belongs to the specific label）? It is just a label's feature vector.
Thank u soooooooo much！: D

**Comment by anshumitts** [comment]
Hi @wangchichi1999 , Thank you for appreciating our work. Now for your question. For an input point, ECLARE first shortlists O(log L ) labels using Module 2 and re-rank them using the Final Extreme Classification task. 
-AM

**Comment by wangchichi1999** [comment]
I think I got it. Thanks for your answering !
