### ISSUE TITLE
Error Dimensions

### ISSUE THREAD

**Issue by hdm30** [Extreme-classification/ECLARE#5]
Hello,

I tried ECLARE model on custom dataset for multilabel classification task. I encountered the following error after running the code:

Traceback (most recent call last):
  File "/root/scratch/XC/programs/ECLARE/ECLARE/main.py", line 213, in <module>
    main(args.params)
  File "/root/scratch/XC/programs/ECLARE/ECLARE/main.py", line 194, in main
    train(model, params)
  File "/root/scratch/XC/programs/ECLARE/ECLARE/main.py", line 58, in train
    model.fit(
  File "/root/scratch/XC/programs/ECLARE/ECLARE/libs/model_base.py", line 373, in fit
    self._fit(train_dataset, valid, model_dir, result_dir, validate_after)
  File "/root/scratch/XC/programs/ECLARE/ECLARE/libs/model_base.py", line 305, in _fit
    self._train_depth(train_ds, valid_ds, model_dir,
  File "/root/scratch/XC/programs/ECLARE/ECLARE/libs/model_base.py", line 288, in _train_depth
    tr_avg_loss = self._step(train_dl)
  File "/root/scratch/XC/programs/ECLARE/ECLARE/libs/model_base.py", line 196, in _step
    loss = self._compute_loss(out_ans, batch_data)
  File "/root/scratch/XC/programs/ECLARE/ECLARE/libs/model_base.py", line 183, in _compute_loss
    return self.criterion(out_ans, _true).to(device)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/loss.py", line 713, in forward
    return F.binary_cross_entropy_with_logits(input, target,
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/functional.py", line 3130, in binary_cross_entropy_with_logits
    raise ValueError("Target size ({}) must be the same as input size ({})".format(target.size(), input.size()))

I have no idea why the target size mismatch the input size?!
Many thanks in advance.

**Comment by anshumitts** [comment]
Can you share the dataset? If not can you share the dataset statistics #labels etc? Please share the config file you are using from training. Are you facing the same issue while running with public datasets?

**Comment by hdm30** [comment]
Thank you for your reply. Unfortunately i can't share the dataset it isn't public. the labels are text representations of patent labels : https://www.wipo.int/classifications/ipc/en/ITsupport/Version20170101/transformations/ipc/20170101/en/htm/A01B.htm
I didn't have this issue when i tried LF-AmazonTitles131K dataset.

here is the config file:
{
    "SETUP": {
        "vocabulary_dims": {
            "action": "size",
            "over": "feature_indices"
        },
        "label_features": {
            "action": "size",
            "over": "v_lbl_fts"
        },
        "num_labels": {
            "action": "size",
            "over": "label_indices"
        }
    },
    "DEFAULT": {
        "feature_type": "sparse",
        "embedding_dims": 300,
        "dlr_factor": 0.5,
        "num_labels": 6621,
        "A": 0.6,
        "B": 2.6,
        "filter_labels": "filter_labels_test.txt",
        "b_factors": [
            17
        ],
        "beam_size": 50,
        "cluster_method": "AugParabel",
        "num_trees": 3,
        "optim": "Adam",
        "tr_feat_fname": "trn_X_Xf.txt",
        "tr_label_fname": "trn_X_Y.txt",
        "ts_feat_fname": "tst_X_Xf.txt",
        "ts_label_fname": "tst_X_Y.txt",
        "val_feat_fname": "tst_X_Xf.txt",
        "val_label_fname": "tst_X_Y.txt",
        "label_words": "Yf.txt",
        "force_shallow": true,
        "model_method": "parabel",
        "normalize": true,
        "momentum": 0.9,
        "weight_decay": 0,
        "num_workers": 6,
        "keep_invalid": false,
        "validate_after": 5,
        "validate": true,
        "degree": 2,
        "prune_max_dist": 1.0,
        "decay": 0.0,
        "p_reset": 0.8,
        "walk_len": 400,
        "top_k": 5cd ..,
        "verbose": 500,
        "traverse": true,
        "graph_comp": [
            "trn_X_Y.txt"
        ],
        "lbl_cnt": null,
        "graph_name": "graph.npz",
        "embeddings": "#ARGS.data_dir;/#ARGS.dataset;/random",
        "feature_indices": "#ARGS.data_dir;/#ARGS.dataset;/g-xml_data/features_split.txt",
        "label_indices": "#ARGS.data_dir;/#ARGS.dataset;/g-xml_data/labels_split.txt",
        "v_lbl_fts": "#ARGS.data_dir;/#ARGS.dataset;/g-xml_data/v_lbs_fts_split.txt"
    },
    "ECLARE-S": {
        "freeze_embeddings": false,
        "dropout": 0.2,
        "batch_sizes": [
            64
        ],
        "depth_lrs": [
            0.005
        ],
        "call_backs": [
            20
        ],
        "dlr_steps": [
            10
        ],
        "layers": [
            "ECLAREh"
        ],
        "trans_method": "./json/BoWJson-Surrogate.json",
        "use_classifier_wts": false
    },
    "ECLARE": {
        "embeddings": "#ARGS.emb_dir;/embeddings.pkl",
        "freeze_embeddings": false,
        "dropout": 0.2,
        "batch_sizes": [
            64,
            64
        ],
        "depth_lrs": [
            0.004,
            0.004
        ],
        "call_backs": [
            10,
            10
        ],
        "dlr_steps": [
            5,
            5
        ],
        "layers": [
            "ECLAREh",
            "ECLAREt"
        ],
        "trans_method": "./json/BoWJson.json",
        "use_classifier_wts": true,
        "lbl_cnt": "#ARGS.model_dir;/label_centroids.npy"
    }
}


Many thanks in advance.

**Comment by hdm30** [comment]
I would like to mention that there is 6621 labels in our dataset

**Comment by hdm30** [comment]
Could you please spot where the problem lies? Many thanks in advance.

**Comment by ZoeYou** [comment]
Hello, it seems that the problem of dimension appears when the number of labels in training data and testing dataset is different.

I have the number of labels in training set = 6556 and the number of labels in testing set and validation set = 4492, and I have errors like this:

  ```
/home/yzuo/scratch/XC/models/ECLARE/INPI_title_desc_2020_6_wiki_maxInputLength-1500_featureDim-50000/v_ECLARE_RUN/surrogate/graph.npz
/home/yzuo/scratch/XC/data/INPI_title_desc_2020_6_wiki_maxInputLength-1500_featureDim-50000/random
Using random init
/home/yzuo/scratch/XC/programs/ECLARE/ECLARE/main.py:47: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  indices = np.loadtxt(params.feature_indices, dtype=np.int)
Model parameters:  Namespace(A=0.6, B=2.6, b_factors=[15], batch_sizes=[255], beam_size=20, call_backs=[20], cluster_method='AugParabel', config='ECLARE/INPI_title_desc_2020_6_wiki_maxInputLength-1500_featureDim-50000.json', data_dir='/home/yzuo/scratch/XC/data', dataset='INPI_title_desc_2020_6_wiki_maxInputLength-1500_featureDim-50000', decay=0.0, degree=2, depth_lrs=[0.005], dlr_factor=0.5, dlr_steps=[10], dropout=0.2, emb_dir='random', embedding_dims=300, embeddings='/home/yzuo/scratch/XC/data/INPI_title_desc_2020_6_wiki_maxInputLength-1500_featureDim-50000/random', feature_indices='/home/yzuo/scratch/XC/data/INPI_title_desc_2020_6_wiki_maxInputLength-1500_featureDim-50000/g-xml_data/features_split.txt', feature_type='sparse', filter_labels='filter_labels_test.txt', force_shallow=True, freeze_embeddings=False, graph_comp=['trn_X_Y.txt'], graph_name='graph.npz', keep_invalid=False, label_features=50000, label_indices='/home/yzuo/scratch/XC/data/INPI_title_desc_2020_6_wiki_maxInputLength-1500_featureDim-50000/g-xml_data/labels_split.txt', label_padding_index=6556, label_words='Yf.txt', layers=['ECLAREh'], lbl_cnt=None, mode='train', model_dir='/home/yzuo/scratch/XC/models/ECLARE/INPI_title_desc_2020_6_wiki_maxInputLength-1500_featureDim-50000/v_ECLARE_RUN/surrogate', model_fname='ECLARE-S', model_method='parabel', momentum=0.9, normalize=True, num_labels=6556, num_trees=3, num_workers=6, optim='Adam', p_reset=0.8, pred_fname='test_predictions', propagate=10, prune_max_dist=1.0, result_dir='/home/yzuo/scratch/XC/results/ECLARE/INPI_title_desc_2020_6_wiki_maxInputLength-1500_featureDim-50000/v_ECLARE_RUN/surrogate', top_k=10, tr_feat_fname='trn_X_Xf.txt', tr_label_fname='trn_X_Y.txt', trans_method='./json/BoWJson-Surrogate.json', traverse=True, tree_idx=-1, ts_feat_fname='tst_X_Xf.txt', ts_label_fname='tst_X_Y.txt', use_classifier_wts=False, v_lbl_fts='/home/yzuo/scratch/XC/data/INPI_title_desc_2020_6_wiki_maxInputLength-1500_featureDim-50000/g-xml_data/v_lbs_fts_split.txt', val_feat_fname='tst_X_Xf.txt', val_label_fname='tst_X_Y.txt', validate=True, validate_after=5, verbose=500, vocabulary_dims=50000, walk_len=400, weight_decay=0)
Loading from pre-build file
/scratch/yzuo/XC/programs/ECLARE/ECLARE/libs/utils.py:26: UserWarning: loadtxt: Empty input file: "/home/yzuo/scratch/XC/data/INPI_title_desc_2020_6_wiki_maxInputLength-1500_featureDim-50000/filter_labels_test.txt"
  filter_lbs = np.loadtxt(os.path.join(
Overlap is: 0
INFO:ECLARE-S:Loading training data.
Valid labels after processing:  6556
Simple: This is a simple shortlist handler
INFO:ECLARE-S:Loading validation data.
/home/yzuo/.local/lib/python3.8/site-packages/xclib-0.97-py3.8-linux-x86_64.egg/xclib/data/data_utils.py:263: UserWarning: Header mis-match from inferred shape!
  warnings.warn("Header mis-match from inferred shape!")
/home/yzuo/.local/lib/python3.8/site-packages/xclib-0.97-py3.8-linux-x86_64.egg/xclib/utils/sparse.py:109: UserWarning: Header mis-match from inferred shape!
  warnings.warn("Header mis-match from inferred shape!")
Traceback (most recent call last):
  File "/home/yzuo/scratch/XC/programs/ECLARE/ECLARE/main.py", line 213, in <module>
    main(args.params)
  File "/home/yzuo/scratch/XC/programs/ECLARE/ECLARE/main.py", line 194, in main
    train(model, params)
  File "/home/yzuo/scratch/XC/programs/ECLARE/ECLARE/main.py", line 58, in train
    model.fit(
  File "/scratch/yzuo/XC/programs/ECLARE/ECLARE/libs/model_base.py", line 361, in fit
    valid = self._create_dataset(
  File "/scratch/yzuo/XC/programs/ECLARE/ECLARE/libs/model_base.py", line 138, in _create_dataset
    _dataset = construct_dataset(
  File "/scratch/yzuo/XC/programs/ECLARE/ECLARE/libs/dataset.py", line 20, in construct_dataset
    return DatasetGraph(
  File "/scratch/yzuo/XC/programs/ECLARE/ECLARE/libs/dataset.py", line 367, in __init__
    super().__init__(data_dir, fname_features, fname_labels, data,
  File "/scratch/yzuo/XC/programs/ECLARE/ECLARE/libs/dataset.py", line 85, in __init__
    super().__init__(data_dir, fname_features, fname_labels, data,
  File "/scratch/yzuo/XC/programs/ECLARE/ECLARE/libs/dataset_base.py", line 19, in __init__
    self.features, self.labels = self.load_data(
  File "/scratch/yzuo/XC/programs/ECLARE/ECLARE/libs/dataset_base.py", line 83, in load_data
    labels = self.load_labels(
  File "/scratch/yzuo/XC/programs/ECLARE/ECLARE/libs/dataset_base.py", line 65, in load_labels
    labels = construct_l(data_dir, fname, Y, normalize_labels,
  File "/scratch/yzuo/XC/programs/ECLARE/ECLARE/libs/labels.py", line 33, in construct
    return GraphLabels(data_dir, fname, Y, normalize)
  File "/scratch/yzuo/XC/programs/ECLARE/ECLARE/libs/labels.py", line 197, in __init__
    super().__init__(data_dir, fname, Y)
  File "/scratch/yzuo/XC/programs/ECLARE/ECLARE/libs/labels.py", line 51, in __init__
    self.Y = self.load(data_dir, fname, Y)
  File "/scratch/yzuo/XC/programs/ECLARE/ECLARE/libs/labels.py", line 72, in load
    return data_utils.read_sparse_file(
  File "/home/yzuo/.local/lib/python3.8/site-packages/xclib-0.97-py3.8-linux-x86_64.egg/xclib/data/data_utils.py", line 283, in read_sparse_file
    X = csr_matrix((data, (rows, cols)), shape=_header_shape)
  File "/home/yzuo/miniconda3/envs/pt_env/lib/python3.8/site-packages/scipy/sparse/compressed.py", line 57, in __init__
    other = self.__class__(coo_matrix(arg1, shape=shape))
  File "/home/yzuo/miniconda3/envs/pt_env/lib/python3.8/site-packages/scipy/sparse/coo.py", line 198, in __init__
    self._check()
  File "/home/yzuo/miniconda3/envs/pt_env/lib/python3.8/site-packages/scipy/sparse/coo.py", line 287, in _check
    raise ValueError('column index exceeds matrix dimensions')
ValueError: column index exceeds matrix dimensions
```

**Comment by anshumitts** [comment]
Dear @ZoeYou and @hdm30 , ECLARE is designed to run on large label space. Given the label space is usually in the millions we use 
"b_factors": [
17
],
which clusters labels space in 65k(2**17) clusters and learn features using these meta labels.
In your problem setting label space is < 10K, so I would suggest using 
"model_method": "NoCluster" instead. 
Let me know if it works
- AM
